CREATE DATABASE EmpresaLog;
USE EmpresaLog;

-- ROL DE ADMINISTRADOR
CREATE USER 'admin'@'localhost' IDENTIFIED BY '12345ñ';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost' WITH GRANT OPTION;        
FLUSH PRIVILEGES;    

SELECT * FROM Filtro_Columnas;
CREATE TABLE Filtro_Columnas (
  nombre       VARCHAR(60) PRIMARY KEY,
  columnas     VARCHAR(512) NOT NULL,   -- índices de columnas, separados por coma (ej: "0,2,9,6")
  usuario      VARCHAR(100) NULL,       -- opcional, por si después quieres por-usuario
  actualizado  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DESCRIBE Carta_Porte;

drop table Carta_Porte;
SELECT * FROM Carta_Porte;
CREATE TABLE Carta_Porte(
Carta_Porte_id INT AUTO_INCREMENT PRIMARY KEY NOT NULL, 
Cliente varchar(100),
Operador VARCHAR(100),
DESTINO VARCHAR(100), 
REFERENCIA VARCHAR (100),
CUSTODIO varchar(100),
FACTURA VARCHAR (100),
FECHA_FACTURA VARCHAR (100),
VALOR DECIMAL(12,2),
FECHA_DE_PAGO VARCHAR(100),
REMITENTE VARCHAR (100),
CONSIGNATORIO VARCHAR(100),
FACTURA2 VARCHAR(100),
PLACA_CABEZAL VARCHAR (50),
PLACA_DEL_FURGON VARCHAR (50),
VALOR_FLETE DECIMAL(12,2),
ANTICIPO DECIMAL(12,2),
A_CANCELACION DECIMAL (12,2),
FECHA_DE_PAGADO VARCHAR(100),
F_DE_CARGA VARCHAR(100),
F_DE_CRUCE VARCHAR(100),
F_SAL_T_U VARCHAR(100),
F_F_DESTINO VARCHAR(100),
F_EN_DESTINO VARCHAR(100), 
F_DESCARGA VARCHAR(100),
F_E_DE_DOCTOS VARCHAR(100), 
PAGADO VARCHAR(50),
OBSERVACIONES VARCHAR (250));



-- Tabla de auditoría única
CREATE TABLE AUDITORIA (
  id             BIGINT AUTO_INCREMENT PRIMARY KEY,
  Carta_Porte_id INT NOT NULL,
  modificado_en  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  usuario        VARCHAR(100) NULL,
  accion         ENUM('INSERT','UPDATE','DELETE') NOT NULL,
  descripcion    VARCHAR(255) NULL,
  detalle        JSON NULL,
  INDEX (Carta_Porte_id),
  INDEX (modificado_en),
  INDEX (accion)
);



DELIMITER //
-- INSERT: snapshot completo en 'nuevo'
CREATE TRIGGER TRIGGER_1
AFTER INSERT ON Carta_Porte
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (Carta_Porte_id, usuario, accion, descripcion, detalle)
  VALUES (
    NEW.Carta_Porte_id,
    COALESCE(@app_user, SUBSTRING_INDEX(CURRENT_USER(), '@', 1)),
    'INSERT',
    CONCAT('Alta de registro ', NEW.Carta_Porte_id),
    JSON_OBJECT(
      'nuevo', JSON_OBJECT(
        'Cliente', NEW.Cliente,
        'Operador', NEW.Operador,
        'DESTINO', NEW.DESTINO,
        'CUSTODIO', NEW.CUSTODIO,
        'FACTURA', NEW.FACTURA,
        'FECHA_FACTURA', NEW.FECHA_FACTURA,
        'VALOR', NEW.VALOR,
        'FECHA_DE_PAGO', NEW.FECHA_DE_PAGO,
        'REMITENTE', NEW.REMITENTE,
        'CONSIGNATORIO', NEW.CONSIGNATORIO,
        'FACTURA2', NEW.FACTURA2,
        'VALOR_FLETE', NEW.VALOR_FLETE,
        'ANTICIPO', NEW.ANTICIPO,
        'A_CANCELACION', NEW.A_CANCELACION,
        'FECHA_DE_PAGADO', NEW.FECHA_DE_PAGADO,
        'F_DE_CARGA', NEW.F_DE_CARGA,
        'F_DE_CRUCE', NEW.F_DE_CRUCE,
        'F_SAL_T_U', NEW.F_SAL_T_U,
        'F_F_DESTINO', NEW.F_F_DESTINO,
        'F_EN_DESTINO', NEW.F_EN_DESTINO,
        'F_DESCARGA', NEW.F_DESCARGA,
        'F_E_DE_DOCTOS', NEW.F_E_DE_DOCTOS,
        'PAGADO', NEW.PAGADO,
        'OBSERVACIONES', NEW.OBSERVACIONES
      )
    )
  );
END //
 
-- UPDATE: sólo campos que cambiaron (campo-por-campo)
CREATE TRIGGER TRIGGER_2
AFTER UPDATE ON Carta_Porte
FOR EACH ROW
BEGIN
  DECLARE cambio JSON;
  SET cambio = JSON_OBJECT();

  IF NOT (OLD.Cliente        <=> NEW.Cliente)        THEN SET cambio = JSON_SET(cambio, '$.Cliente',        JSON_OBJECT('ANTES DEL CAMBIO:', OLD.Cliente,        'despues', NEW.Cliente));        END IF;
  IF NOT (OLD.Operador       <=> NEW.Operador)       THEN SET cambio = JSON_SET(cambio, '$.Operador',       JSON_OBJECT('ANTES DEL CAMBIO:', OLD.Operador,       'DESPUES:', NEW.Operador));       END IF;
  IF NOT (OLD.DESTINO        <=> NEW.DESTINO)        THEN SET cambio = JSON_SET(cambio, '$.DESTINO',        JSON_OBJECT('ANTES DEL CAMBIO:', OLD.DESTINO,        'DESPUES:', NEW.DESTINO));        END IF;
  IF NOT (OLD.CUSTODIO       <=> NEW.CUSTODIO)       THEN SET cambio = JSON_SET(cambio, '$.CUSTODIO',       JSON_OBJECT('ANTES DEL CAMBIO:', OLD.CUSTODIO,       'DESPUES:', NEW.CUSTODIO));       END IF;
  IF NOT (OLD.FACTURA        <=> NEW.FACTURA)        THEN SET cambio = JSON_SET(cambio, '$.FACTURA',        JSON_OBJECT('ANTES DEL CAMBIO:', OLD.FACTURA,        'DESPUES:', NEW.FACTURA));        END IF;
  IF NOT (OLD.FECHA_FACTURA  <=> NEW.FECHA_FACTURA)  THEN SET cambio = JSON_SET(cambio, '$.FECHA_FACTURA',  JSON_OBJECT('ANTES DEL CAMBIO:', OLD.FECHA_FACTURA,  'DESPUES:', NEW.FECHA_FACTURA));  END IF;
  IF NOT (OLD.VALOR          <=> NEW.VALOR)          THEN SET cambio = JSON_SET(cambio, '$.VALOR',          JSON_OBJECT('ANTES DEL CAMBIO:', OLD.VALOR,          'DESPUES:', NEW.VALOR));          END IF;
  IF NOT (OLD.FECHA_DE_PAGO  <=> NEW.FECHA_DE_PAGO)  THEN SET cambio = JSON_SET(cambio, '$.FECHA_DE_PAGO',  JSON_OBJECT('ANTES DEL CAMBIO:', OLD.FECHA_DE_PAGO,  'DESPUES:', NEW.FECHA_DE_PAGO));  END IF;
  IF NOT (OLD.REMITENTE      <=> NEW.REMITENTE)      THEN SET cambio = JSON_SET(cambio, '$.REMITENTE',      JSON_OBJECT('ANTES DEL CAMBIO:', OLD.REMITENTE,      'DESPUES:', NEW.REMITENTE));      END IF;
  IF NOT (OLD.CONSIGNATORIO  <=> NEW.CONSIGNATORIO)  THEN SET cambio = JSON_SET(cambio, '$.CONSIGNATORIO',  JSON_OBJECT('ANTES DEL CAMBIO:', OLD.CONSIGNATORIO,  'DESPUES:', NEW.CONSIGNATORIO));  END IF;
  IF NOT (OLD.FACTURA2       <=> NEW.FACTURA2)       THEN SET cambio = JSON_SET(cambio, '$.FACTURA2',       JSON_OBJECT('ANTES DEL CAMBIO:', OLD.FACTURA2,       'DESPUES:', NEW.FACTURA2));       END IF;
  IF NOT (OLD.VALOR_FLETE    <=> NEW.VALOR_FLETE)    THEN SET cambio = JSON_SET(cambio, '$.VALOR_FLETE',    JSON_OBJECT('ANTES DEL CAMBIO:', OLD.VALOR_FLETE,    'DESPUES:', NEW.VALOR_FLETE));    END IF;
  IF NOT (OLD.ANTICIPO       <=> NEW.ANTICIPO)       THEN SET cambio = JSON_SET(cambio, '$.ANTICIPO',       JSON_OBJECT('ANTES DEL CAMBIO:', OLD.ANTICIPO,       'DESPUES:', NEW.ANTICIPO));       END IF;
  IF NOT (OLD.A_CANCELACION  <=> NEW.A_CANCELACION)  THEN SET cambio = JSON_SET(cambio, '$.A_CANCELACION',  JSON_OBJECT('ANTES DEL CAMBIO:', OLD.A_CANCELACION,  'DESPUES:', NEW.A_CANCELACION));  END IF;
  IF NOT (OLD.FECHA_DE_PAGADO<=> NEW.FECHA_DE_PAGADO)THEN SET cambio = JSON_SET(cambio, '$.FECHA_DE_PAGADO',JSON_OBJECT('ANTES DEL CAMBIO:', OLD.FECHA_DE_PAGADO,'DESPUES:', NEW.FECHA_DE_PAGADO));END IF;
  IF NOT (OLD.F_DE_CARGA     <=> NEW.F_DE_CARGA)     THEN SET cambio = JSON_SET(cambio, '$.F_DE_CARGA',     JSON_OBJECT('ANTES DEL CAMBIO:', OLD.F_DE_CARGA,     'DESPUES:', NEW.F_DE_CARGA));     END IF;
  IF NOT (OLD.F_DE_CRUCE     <=> NEW.F_DE_CRUCE)     THEN SET cambio = JSON_SET(cambio, '$.F_DE_CRUCE',     JSON_OBJECT('ANTES DEL CAMBIO:', OLD.F_DE_CRUCE,     'DESPUES:', NEW.F_DE_CRUCE));     END IF;
  IF NOT (OLD.F_SAL_T_U      <=> NEW.F_SAL_T_U)      THEN SET cambio = JSON_SET(cambio, '$.F_SAL_T_U',      JSON_OBJECT('ANTES DEL CAMBIO:', OLD.F_SAL_T_U,      'DESPUES:', NEW.F_SAL_T_U));      END IF;
  IF NOT (OLD.F_F_DESTINO    <=> NEW.F_F_DESTINO)    THEN SET cambio = JSON_SET(cambio, '$.F_F_DESTINO',    JSON_OBJECT('ANTES DEL CAMBIO:', OLD.F_F_DESTINO,    'DESPUES:', NEW.F_F_DESTINO));    END IF;
  IF NOT (OLD.F_EN_DESTINO   <=> NEW.F_EN_DESTINO)   THEN SET cambio = JSON_SET(cambio, '$.F_EN_DESTINO',   JSON_OBJECT('ANTES DEL CAMBIO:', OLD.F_EN_DESTINO,   'DESPUES:', NEW.F_EN_DESTINO));   END IF;
  IF NOT (OLD.F_DESCARGA     <=> NEW.F_DESCARGA)     THEN SET cambio = JSON_SET(cambio, '$.F_DESCARGA',     JSON_OBJECT('ANTES DEL CAMBIO:', OLD.F_DESCARGA,     'DESPUES:', NEW.F_DESCARGA));     END IF;
  IF NOT (OLD.F_E_DE_DOCTOS  <=> NEW.F_E_DE_DOCTOS)  THEN SET cambio = JSON_SET(cambio, '$.F_E_DE_DOCTOS',  JSON_OBJECT('ANTES DEL CAMBIO:', OLD.F_E_DE_DOCTOS,  'DESPUES:', NEW.F_E_DE_DOCTOS));  END IF;
  IF NOT (OLD.PAGADO         <=> NEW.PAGADO)         THEN SET cambio = JSON_SET(cambio, '$.PAGADO',         JSON_OBJECT('ANTES DEL CAMBIO:', OLD.PAGADO,         'DESPUES:', NEW.PAGADO));         END IF;
  IF NOT (OLD.OBSERVACIONES  <=> NEW.OBSERVACIONES)  THEN SET cambio = JSON_SET(cambio, '$.OBSERVACIONES',  JSON_OBJECT('ANTES DEL CAMBIO:', OLD.OBSERVACIONES,  'DESPUES:', NEW.OBSERVACIONES));  END IF;

  INSERT INTO AUDITORIA (Carta_Porte_id, usuario, accion, descripcion, detalle)
  VALUES (
    NEW.Carta_Porte_id,
    COALESCE(@app_user, SUBSTRING_INDEX(CURRENT_USER(), '@', 1)),
    'UPDATE',
    CONCAT('Actualización de registro ', NEW.Carta_Porte_id),
    NULLIF(cambio, JSON_OBJECT())
  );
END //

-- DELETE: snapshot completo en 'eliminado'
CREATE TRIGGER TRIGGER_3
AFTER DELETE ON Carta_Porte
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (Carta_Porte_id, usuario, accion, descripcion, detalle)
  VALUES (
    OLD.Carta_Porte_id,
    COALESCE(@app_user, SUBSTRING_INDEX(CURRENT_USER(), '@', 1)),
    'DELETE',
    CONCAT('Eliminación de registro ', OLD.Carta_Porte_id),
    JSON_OBJECT(
      'eliminado', JSON_OBJECT(
        'Cliente', OLD.Cliente,
        'Operador', OLD.Operador,
        'DESTINO', OLD.DESTINO,
        'CUSTODIO', OLD.CUSTODIO,
        'FACTURA', OLD.FACTURA,
        'FECHA_FACTURA', OLD.FECHA_FACTURA,
        'VALOR', OLD.VALOR,
        'FECHA_DE_PAGO', OLD.FECHA_DE_PAGO,
        'REMITENTE', OLD.REMITENTE,
        'CONSIGNATORIO', OLD.CONSIGNATORIO,
        'FACTURA2', OLD.FACTURA2,
        'VALOR_FLETE', OLD.VALOR_FLETE,
        'ANTICIPO', OLD.ANTICIPO,
        'A_CANCELACION', OLD.A_CANCELACION,
        'FECHA_DE_PAGADO', OLD.FECHA_DE_PAGADO,
        'F_DE_CARGA', OLD.F_DE_CARGA,
        'F_DE_CRUCE', OLD.F_DE_CRUCE,
        'F_SAL_T_U', OLD.F_SAL_T_U,
        'F_F_DESTINO', OLD.F_F_DESTINO,
        'F_EN_DESTINO', OLD.F_EN_DESTINO,
        'F_DESCARGA', OLD.F_DESCARGA,
        'F_E_DE_DOCTOS', OLD.F_E_DE_DOCTOS,
        'PAGADO', OLD.PAGADO,
        'OBSERVACIONES', OLD.OBSERVACIONES
      )
    )
  );
END //
DELIMITER ;




 



